### ISSUE TITLE
생활 법령 백문백답 데이터 수집 질문

### ISSUE THREAD

**Issue by HanNayeoniee** [juicyjung/LAW-Alpaca#1]
안녕하세요, juicyjung님!
법률 데이터와 모델을 공유해주셔서 감사합니다 :D

업로드하신 huggingface dataset과 생활법령 페이지의 답변이 조금 달라서 질문드립니다.
같은 instruction(질문)에 대해 huggingface dataset은 생활 법령 백문백답의 답변 중 일부만 포함되어 있는 것 같은데, 답변에서 참고한 법령이나 약관은 따로 수집하지 않으셨나요?
혹시 약관을 수집하지 않은 이유가 따로 있는지도 궁금합니다.

미리 답변 감사합니다!
(아래는 제가 다르다고 생각한 데이터 예시입니다)

- instruction(question): 자녀의 온라인학습 사이트에서 1년 계약을 했습니다. 수강 시작 전 개인적인 사정으로 해지를 요청했더니 사업자가 6개월은 수강 의무 사용기간이라며 위약금을 청구합니다. 위약금 공제 없이 환급은 어려운가요?
- huggingface output: 가입 시 개별약정을 확인해야 하고, 이러한 기준이 없다면 표준약관을 확인하고 가입하시는 것이 좋습니다. 온라인학습자는 온라인학습 사이트 운영자로부터 이용신청확인 통지를 받은 날부터 7일 내에는 온라인학습 이용계약의 청약을 철회할 수 있고, 위약금이나 손해배상을 하지 않아도 됩니다.
- [사이트 정답](https://www.easylaw.go.kr/CSP/OnhunqueansInfoRetrieve.laf?onhunqueSeq=5771&onhunqnaAstSeq=89&targetRow=1&sortType=&pagingType=)

**Comment by jiwoochris** [comment]
안녕하세요 나연님!

Law-Alpaca 레포에 관심 가져주셔서 감사합니다 ㅎㅎ

생활법령 100문 100답 사이트에는

1. 질문
2. 질문에 대한 답변
3. 참고 자료

가 있습니다.

저희가 수집한 데이터는 1. 질문과 2. 질문에 대한 답변이고, 나연님이 말씀해주신 것처럼 3. 참고 자료는 따로 수집하지 않았습니다.

왜냐하면 이 데이터셋을 만든 목적이 여러 LLM을 파인튜닝하기 위한 대화형 데이터셋이 필요했기 때문인데, 너무 길면 학습에 노이즈가 될 것 같아서 3. 참고 자료는 빼고 수집하는 방향으로 진행했습니다..ㅎㅎ

친구랑 대화하는 것처럼 대화만 딱! 뽑아내서 학습시키고 싶었습니다.

근데 사실 데이터 수집을 마친 후에 이왕 하는거 전체를 수집하면 더 좋았겠다는 생각을 많이 하긴 했습니다 ㅋㅎㅋㅎㅋㅎㅋㅎ


또 궁금한게 생기면 편하게 연락 주세요 ㅎㅎ 감사합니다!

**Comment by HanNayeoniee** [comment]
빠른 답변 감사합니다!!

대화형 모델을 만들기 위해서는 2.질문에 대한 답변 만 사용하는게 자연스럽지만, 답변에 참고한 문서들을 함께 활용하면 신뢰도있는 모델을 만들 수 있다고 생각해 여쭤봤습니다. ㅎㅎ

Open API 신청이 따로 없던데, BeautifulSoup 모듈로 웹크롤링해 데이터를 수집하셨나요??

해당 사이트에 법 관련해 쉽게 설명된 자료들이 많아서 데이터 수집을 고려해 보려고 합니다!

**Comment by jiwoochris** [comment]
저도 찬성합니다..!

데이터 수집 방법은 저는 2. 질문에 대한 답변과 3. 참고 자료를 구분해야 했기 때문에 일일이 직접 복붙을 했는데요..!

생각해보니 BeautifulSoup 모듈로 충분히 구현해볼 수 있을 것 같습니다 ㅎㅎ

크롤링 하신 후 해당 허깅페이스 링크 남겨주시거나 이 레포에 PR해주시면 업데이트 반영하겠습니다..!!

다시 한번 관심 가져주셔서 감사합니다!!

**Comment by HanNayeoniee** [comment]
저는 일일이 복붙할 자신이 없는데 대단하십니다!!

크롤링 성공적으로 된다면 이슈나 PR남기도록 하겠습니다.

다시 한번 답변 감사합니다!!
